name: Xbox CI
on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.7

jobs:
  xbox:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/AliAlafandy/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
        
      - name: Rebuild Lime (x86)
        run: haxelib run lime rebuild uwp -32 -release -nocolor -nocffi
        shell: cmd

      - name: Upload Artifact (UWP x86)
        uses: actions/upload-artifact@v4
        with:
          name: WinRT-NDLL
          path: ndll/WinRT/   # This is where Lime puts -32 builds
          if-no-files-found: error

      - name: Rebuild Lime (x64)
        run: haxelib run lime rebuild uwp -64 -release -nocolor -nocffi
        shell: cmd

      - name: Upload Artifact (UWP x64)
        uses: actions/upload-artifact@v4
        with:
          name: WinRT64-NDLL
          path: ndll/WinRT64/ # This is where Lime puts -64 builds
          if-no-files-found: error
